language: python
python:
- '3.6'
install:
- python3 setup.py install
- pip install codecov
script:
- python3 setup.py nosetests
- codecov
deploy:
  provider: pypi
  user: cwendt94
  password:
    secure: DonQ4RVuTIwSGi7G9ESmpH1G7wcgBT3I4MC9qHWTLh7KpvLaS8FtTe8CQsXqWpxKNa5pNSDMUpKrDjCPqautLqxHuy8Z7hqnxbNR1SAlsW3dB+Mo8R4pJY4dTQxQtQv0JW0skag1tElX6TxG8wcnujNS/1pMeLu5vGbTIQDPQDOstPsf0h0KPWWlNRr7Z8IwPKD2udS5lpbAEvMj4Y+mPsLCFGarOt8JjsMGQLFletCp8UUeGSB8dEYFGAuMZKaMASeHRltH+wL758WmEbITQ6eB+wnhr89iJgxWGAn3+0bJc949WTMkS4j32k3Ex+cMr0IwUdZckE0VG5J2qIFBcJZwwQCXV9RpNV6VOK/b1wOIw8nugtLkZ0815EiOHJPucn1y92Hc6Erjnz5SL+VMpv/TSZSjkNSlc8FdDlIihoWZV6JBl3oLJHyR7aCFgplnr1kdEhvY2rvsPnV0IxTayYJkvgsYaIgtp8QwUwHhPPc091prBGrAxURfEORgVOzz06f5Nu9kwqfycH1Oj/1CeRFaOk+PmtTAqduYhSgkRuzGv5gkU01RKA2CR7kncAAUnQ4Z9GwikpppYTbEA5qb3PR/ZFa5UWpXoGyIkH1ncOfw0+HwM2x81Y+7qjUNU9b5GFh9hk4o1GKL/o5Qca8mO+21LoCChNgkV+1D2PgvOYM=
