name:  ✨ Feature request
description: Suggest an idea for this project
issue_body: false 

body:
- type: dropdown
  attributes:
     label: Sport
     options:
     - Football
     - Basketball
     - Baseball
     - Hockey
   validations:
     required: true

- type: textarea
  attributes:
    label: Summary
    description: Describe the new feature/improvement briefly below.
  validations:
    required: true