name: Python package release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        pip install twine==3.8.0
        pip install wheel==0.37.0

    - name: Build Python package
      run: python setup.py bdist_wheel

    - name: Twine check
      run: twine check dist/*
    
    - name: Publish to PyPI
      run: twine upload dist/* -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
